Repository boostcampwm-2024/web03-CorinEE, pull requests merged in 2024-11, with the labels that each got.

#9 [chore] eslint, prettier 설정
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/prettier/package.json
  package.json
  packages/client/eslint.config.js
  packages/server/.eslintrc.js
  packages/server/src/main.ts
  yarn.lock
Labels: 🛠chore

#56 [BE] feature #52, #55 - 호가창 websocket 연결, 코인 종목 api
  .github/workflows/CICD.yml
  docker-compose.yml
  packages/server/common/upbit.ts
  packages/server/src/upbit/coin-list.service.ts
  packages/server/src/upbit/coin-ticker-websocket.service.spec.ts
  packages/server/src/upbit/coin-ticker-websocket.service.ts
  packages/server/src/upbit/orderbook-websocket.service.spec.ts
  packages/server/src/upbit/orderbook-websocket.service.ts
  packages/server/src/upbit/sse.service.ts
  packages/server/src/upbit/upbit.controller.ts
  packages/server/src/upbit/upbit.module.ts
  packages/server/src/upbit/upbit.service.ts
Labels: 📟 backend, 💡feat

#58 [FE] - feature#39 비트코인 차트 구현(일/주/월/년), 차트 반응형 구현
  packages/client/package.json
  packages/client/src/api/coin.ts
  packages/client/src/hooks/usePeriodChart.ts
  packages/client/src/pages/trade/Trade.tsx
  packages/client/src/pages/trade/components/Chart.tsx
  packages/client/src/pages/trade/components/OrderBook.tsx
  packages/client/src/pages/trade/components/chart/CandleChart.tsx
  packages/client/src/pages/trade/components/chart/Chart.tsx
  packages/client/src/pages/trade/components/chart/ChartSelector.tsx
  packages/client/src/pages/trade/components/chart/ChartSkeleton.tsx
  packages/client/src/pages/trade/components/chart/chartSetup.ts
  packages/client/src/pages/trade/components/chart/config.ts
  packages/client/src/pages/trade/components/order_form/OrderForm.tsx
  packages/client/src/pages/trade/components/trade_header/CoinInfo.tsx
  packages/client/src/pages/trade/components/trade_header/TradeHeader.tsx
  packages/client/src/types/chart.ts
  packages/client/src/types/ticker.ts
  packages/client/src/utility/formatCandleData.ts
  yarn.lock
Labels: 💡feat, ⚛️ frontend

#83 [BE] - Feature be #35 마이페이지 api 작성
  packages/server/src/account/account.controller.ts
  packages/server/src/account/account.module.ts
  packages/server/src/account/account.service.ts
  packages/server/src/account/dtos/myAccount.dto.ts
Labels: 📟 backend, 💡feat

#87 [BE] - Feature be #38 미체결 api 구현
  packages/server/src/trade/dtos/tradeData.dto.ts
  packages/server/src/trade/trade.controller.ts
  packages/server/src/trade/trade.service.ts
Labels: 📟 backend, 💡feat

#133 [BE] - Feature be #131 account, asset, favorite 리팩토링
  packages/server/.eslintrc.js
  packages/server/src/account/account.controller.ts
  packages/server/src/account/account.repository.ts
  packages/server/src/account/account.service.ts
  packages/server/src/account/constants/currency.constants.ts
  packages/server/src/account/dtos/my-account.dto.ts
  packages/server/src/account/dtos/my-account.response.dto.ts
  packages/server/src/asset/asset.repository.ts
  packages/server/src/configs/winston.config.ts
  packages/server/src/favorite/dtos/favorite.dto.ts
  packages/server/src/favorite/favorite.controller.ts
  packages/server/src/favorite/favorite.service.ts
  packages/server/src/trade-history/dtos/trade-history.dto.ts
  packages/server/src/trade-history/trade-history.controller.ts
  packages/server/src/trade-history/trade-history.module.ts
  packages/server/src/trade-history/trade-history.repository.ts
  packages/server/src/trade-history/trade-history.service.ts
  packages/server/src/trade/trade-ask-bid.service.ts
  packages/server/src/trade/trade-bid.service.ts
  packages/server/src/trade/trade.controller.ts
  packages/server/src/trade/trade.service.ts
  packages/server/src/upbit/SSE/base-web-socket.service.ts
  packages/server/src/upbit/SSE/coin-ticker-websocket.service.ts
  packages/server/src/upbit/SSE/orderbook-websocket.service.ts
  packages/server/src/upbit/SSE/sse.service.ts
  packages/server/src/upbit/chart.service.ts
  packages/server/src/upbit/coin-data-updater.service.ts
  packages/server/src/upbit/coin-list.service.ts
  packages/server/src/upbit/constants.ts
  packages/server/src/upbit/upbit.controller.ts
  packages/server/src/upbit/utils/validation.ts
Labels: 📟 backend, 🔧 refactor
